New Coq plugin for general proof automation
coq/opam-coq-archive pull request #1766
Opened 2021-06-30 16:53 UTC by ckeller

This PR introduces an opam package for `sniper`, a new Coq plugin for general proof automation extending the `SMTCoq` plugin

2021-06-30 19:01 UTC, silene requested changes

2021-06-30 19:01 UTC, silene commented on extra-dev/packages/coq-sniper/coq-sniper.dev+8.13/opam
> +  "coq-metacoq" {= "1.0~beta2+8.13"}
Is there a reason to force such a very specific version of MetaCoq? Are you expecting your package to break with the actual 1.0 release of MetaCoq?

2021-06-30 19:07 UTC, silene commented on extra-dev/packages/coq-sniper/coq-sniper.dev+8.11+8.12/opam
> +  "keyword: automation"
It seems some .vo files get installed, so there should be a tag `"logpath:Sniper"`.

2021-07-01 04:52 UTC, ckeller commented
Hi @silene 
I applied all the changes (and also corrected a (very bad) typo) except about the 1.0 release of Metacoq: I do not see this release? In opam, all the versions have ~alpha or ~beta.

2021-07-01 05:07 UTC, silene commented
What I meant is that your `dev` package will be stuck forever with MetaCoq `1.0~beta2`. So, unless you are already sure that Sniper will be incompatible with the actual 1.0 release of MetaCoq, there is absolutely no reason to put such a harsh constraint. It should instead be `>= "1.0~beta2"`, `>= "1.0~beta"`, or just nothing, depending on how incompatible Sniper is with the various prereleases of MetaCoq.

2021-07-01 08:08 UTC, ckeller commented
I thought it was safer to update the `opam` file after checking that everything is fine, but ok, I have removed the required version.

2021-07-01 13:35 UTC, silene commented
One job failed due to dependencies (I expected this one), but the three other ones timed out. This is a bit worrying. Is it really supposed to take more than three hours to compile Sniper and its dependencies or is there an issue with the Opam package?

2021-07-01 13:37 UTC, silene commented
Related (and perhaps naive) question: Do you need the full-blown MetaCoq or is a subset of it (e.g., `meta-coq-template`) sufficient for Sniper?

2021-07-01 16:28 UTC, ckeller commented
On my computer, it takes approximately 20 minutes to build everything. The longer is indeed MetaCoq, we can restrict to three packages for the moment if needed.

2021-07-02 05:14 UTC, merged

2021-07-02 05:16 UTC, silene commented
I have merged the pull request in the meantime. But it would be great to reduce the dependencies to those strictly needed, in a followup patch. By the way, the dependency on OCaml should also be removed, since Sniper does not provide any OCaml file, as far as I can tell.