Add stable version of package coq-unimath
coq/opam-coq-archive pull request #1789
Opened 2021-08-06 14:06 UTC by maggesi

2021-08-06 15:44 UTC, palmskog commented
@maggesi the layout document for the `released` repository states:
> The repository contains packages for Coq and for Coq extensions that were officially released by the Coq team or their corresponding authors.

I see no evidence that the commit the package uses was in any way officially released by the UniMath team. In particular, the version name of the package has no obvious connection to the commit.

Hence, my interpretation is that this package is not allowed in the `released` repo unless you make an official release (tarball) on GitHub or some other stable location. @gares what's your opinion?

2021-08-06 20:51 UTC, benediktahrens commented
@palmskog : thanks a lot for your explanation. @dangrayson and I will make an official release of UniMath. Is it sufficient to use Github's "release" feature, which is, if I understand correctly, a git tag with some meta-information?

2021-08-06 20:56 UTC, palmskog commented
@benediktahrens GitHub's release mechanism is essentially a thin layer on top of git tags, so it would be enough for the present purposes if you make a tag in the UniMath repository, and GitHub will give you a tarball I can use (see, e.g., https://github.com/coq-community/aac-tactics/tags). However, I recommend using the GitHub release feature to create the tag for you, since it gives some bells and whistles right away, such as nice link to the release on your GitHub repository page.

2021-08-07 08:02 UTC, gares requested changes

2021-08-07 08:02 UTC, gares commented on released/packages/coq-unimath/coq-unimath.20210805/opam
> +  src: "git+https://github.com/UniMath/UniMath.git#7cc41b88e798e9f42af984d8a8abd72c5f955213"
Please give a name to this hash

2021-08-07 21:26 UTC, benediktahrens commented
I have made release 20210807, see https://github.com/UniMath/UniMath/releases/tag/v20210807. 
@maggesi : could you update the PR, please? It requires renaming the directory, I am afraid, as well as updating the source in the opam file. 
@palmskog : what is the policy on cryptographic integrity checking? Should a hash be included?

Thanks a lot for your help, @palmskog , @gares , @maggesi !

2021-08-07 22:43 UTC, palmskog commented
@maggesi here is what I recommend that you use from line 15 in the file:
```
url {
  src: "https://github.com/UniMath/UniMath/archive/refs/tags/v20210807.tar.gz"
  checksum: "sha512=db2f660aea7e4c7eda6d10173173b80d357f994ff148102df6d20b0098e4c4e3ec17f9956700e118b7ff043a4ef29827cccd1fe9f5f54b5f5deaebcac60c666c"
}
```

2021-08-08 07:04 UTC, gares commented on released/packages/coq-unimath/coq-unimath.20210805/opam
> +}
```suggestion
url {
  src: "https://github.com/UniMath/UniMath/archive/refs/tags/v20210807.tar.gz"
  checksum: "sha512=db2f660aea7e4c7eda6d10173173b80d357f994ff148102df6d20b0098e4c4e3ec17f9956700e118b7ff043a4ef29827cccd1fe9f5f54b5f5deaebcac60c666c"
}
```

2021-08-08 07:05 UTC, gares approved these changes

2021-08-08 07:38 UTC, benediktahrens commented
I think the directory name still needs to be changed, the 5 should become a 7.

2021-08-08 08:51 UTC, maggesi commented
@palmskog @gares : Thank you for the help.
Should be ready to merge now.

2021-08-08 10:42 UTC, merged