Add coq-topology.10.0.1 and coq-zorns-lemma.10.0.1
coq/opam-coq-archive pull request #2105
Opened 2022-02-14 13:36 UTC by Columbus240

2022-02-14 14:38 UTC, gares requested changes

2022-02-14 14:38 UTC, gares commented on released/packages/coq-topology/coq-topology.10.0.1/opam
> +version: "dev"
this is incorrect

2022-02-14 14:38 UTC, gares commented on released/packages/coq-zorns-lemma/coq-zorns-lemma.10.0.1/opam
> +version: "dev"
This is wrong, the version is inferred from the directory name

2022-02-14 14:38 UTC, gares commented on released/packages/coq-zorns-lemma/coq-zorns-lemma.10.0.1/opam
> +maintainer: "miloradovsky@gmail.com"
Is this you?

2022-02-15 18:01 UTC, palmskog commented on released/packages/coq-topology/coq-topology.10.0.1/opam
> +version: "dev"
```suggestion
```

2022-02-15 18:01 UTC, palmskog commented on released/packages/coq-zorns-lemma/coq-zorns-lemma.10.0.1/opam
> +maintainer: "miloradovsky@gmail.com"
```suggestion
maintainer: "palmskog@gmail.com"
```

2022-02-15 18:01 UTC, palmskog commented on released/packages/coq-zorns-lemma/coq-zorns-lemma.10.0.1/opam
> +version: "dev"
```suggestion
```

2022-02-15 18:52 UTC, merged