release(Qcert): coq-qcert version 2.2.0
coq/opam-coq-archive pull request #2177
Opened 2022-05-20 17:51 UTC by jeromesimeon

Signed-off-by: Jerome Simeon <jeromesimeon@me.com>

### Q*cert Release 2.2.0

- New experimental WASM backend
- Portability fixes for Coq 8.13 through 8.15

Release notes at: https://github.com/querycert/qcert/releases/tag/v2.2.0

2022-05-20 18:00 UTC, palmskog requested changes
@jeromesimeon please change the file path name to the following:
```
released/packages/coq-qcert/coq-qcert.2.2.0/opam
```
Specifically, there needs to be a period (and not a dash) between `qcert` and `2.2.0` for the version number to be correctly processed.

2022-05-20 18:06 UTC, jeromesimeon commented
> @jeromesimeon please change the file path name to the following:
> 
> ```
> released/packages/coq-qcert/coq-qcert.2.2.0/opam
> ```
> 
> Specifically, there needs to be a period (and not a dash) between `qcert` and `2.2.0` for the version number to be correctly processed.

That's my bad! Fixed now.

2022-05-20 18:31 UTC, palmskog approved these changes

2022-05-20 19:22 UTC, jeromesimeon commented
Seeing a build fail:
```
2140# File "runtimes/javascript/dune", line 25, characters 0-214:
[2141](https://gitlab.com/coq/opam-coq-archive/-/jobs/2486960481#L2141)# 25 | (rule
[2142](https://gitlab.com/coq/opam-coq-archive/-/jobs/2486960481#L2142)# 26 |   (target js_runtime.ml)
[2143](https://gitlab.com/coq/opam-coq-archive/-/jobs/2486960481#L2143)# 27 |   (deps qcert-runtime.js)
[2144](https://gitlab.com/coq/opam-coq-archive/-/jobs/2486960481#L2144)# 28 |   (action
[2145](https://gitlab.com/coq/opam-coq-archive/-/jobs/2486960481#L2145)# 29 |     (with-stdout-to
[2146](https://gitlab.com/coq/opam-coq-archive/-/jobs/2486960481#L2146)# 30 |       js_runtime.ml
[2147](https://gitlab.com/coq/opam-coq-archive/-/jobs/2486960481#L2147)# 31 |       (progn (echo "let runtime = {|\n")
[2148](https://gitlab.com/coq/opam-coq-archive/-/jobs/2486960481#L2148)# 32 |              (cat qcert-runtime.js)
[2149](https://gitlab.com/coq/opam-coq-archive/-/jobs/2486960481#L2149)# 33 |              (echo "|}\n")))))
[2150](https://gitlab.com/coq/opam-coq-archive/-/jobs/2486960481#L2150)# Error: No rule found for runtimes/javascript/qcert-runtime.js
```

investigating...

2022-05-21 13:21 UTC, palmskog commented
@jeromesimeon unfortunately, it looks like *none* of the CI jobs were able to build the release successfully (several jobs did not try, due to the OCaml version constraints).

Since releases must build with at least some stable Coq version, you may want to consider closing the PR and submitting a new PR when the release is fixed. However, I'll leave the PR open for a few more days and you can push changes directly here for that duration.

2022-05-21 17:53 UTC, jeromesimeon commented
> @jeromesimeon unfortunately, it looks like _none_ of the CI jobs were able to build the release successfully (several jobs did not try, due to the OCaml version constraints).
> 
> Since releases must build with at least some stable Coq version, you may want to consider closing the PR and submitting a new PR when the release is fixed. However, I'll leave the PR open for a few more days and you can push changes directly here for that duration.

@palmskog Thanks for the note and leeway. I believe I've identified the issue (due to the use of the `(mode promote)` stanza in a dune file which does not behave quite the same on local or install builds). I've pushed a fix and re-released with the same version number. The GitLab pipeline is running now, so hopefully it goes through this time.

2022-05-22 11:46 UTC, merged