[coq.dev] Use url files instead of rewriting the opam files
coq/opam-coq-archive pull request #2211
Opened 2022-06-29 18:14 UTC by ejgallego

Now that makes the opam files canonical w.r.t. the ones in the opam repos.

See discussion in https://github.com/coq/opam-coq-archive/pull/1923

2022-06-29 19:33 UTC, ejgallego commented
Will merge tomorrow if no one opposes.

2022-06-29 21:17 UTC, palmskog commented
@ejgallego can you explain what is going here? I see a bunch of lines like this:
```
Ignoring core-dev/packages/coq-core/coq-core.dev/url
```
How do we know that the right git repo is actually being used?

2022-06-29 21:20 UTC, gares commented
Can you point me to the doc of this feature? I seem to recall this was how opam1 was working, but not opam2

2022-06-29 21:21 UTC, gares commented
> Now that makes the opam files canonical w.r.t. the ones in the opam repos.

I don't think this is possible. If you find a way, I'm all ears.

2022-06-29 22:30 UTC, erikmd commented
> @ejgallego can you explain what is going on here? I see a bunch of lines like this:
> 
> ```
> Ignoring core-dev/packages/coq-core/coq-core.dev/url
> ```
> 
> How do we know that the right git repo URL is actually being used?

Maybe the warning is just related to the `opam remove` command? which indeed, need not read the `url` file.

2022-06-29 22:32 UTC, erikmd commented
> Can you point me to the doc of this feature? I seem to recall this was how opam1 was working, but not opam2

Indeed this seems to be a feature that dates back to opam1:
https://opam.ocaml.org/doc/1.1/Packaging.html#The-ounit-OPAM-package

but I don't see why it would have been removed from opam 2.1.* → the maintainer that will merge this PR should just test locally I guess (e.g. putting a dummy github url, or the proper one) and that'd be good to go I guess.

2022-06-30 01:08 UTC, silene commented
> but `url` can be just as well be used like before

There are 23.5k packages in the official Opam repository. Not even a single one of them is using a `url` file. We should not be using a feature that is *de facto* unsupported.

2022-06-30 05:38 UTC, gares requested changes
clarify the status of url files with opam upstream

2022-06-30 06:21 UTC, silene commented
This is what Opam's reference manual has to say: "Older versions of opam used `descr` and `url` files besides the `opam` file, and this is still supported, but the preferred way is now to include their information into the `opam` file instead." I guess the only reason these files are still "supported" was to ease the transition from Opam 1 to Opam 2.

Looking at the source code, the `opam` command will forcefully remove from the filesystem any `url` or `descr` file it encounters. (This is especially noticeable in the code of `opam update` and `opam pin`.) The associated comment is "Remove obsolete auxiliary files, in case" [sic].

2022-06-30 11:15 UTC, ejgallego commented
Ok, fair enough, you'll have to use `sed` to sync from canonical `.opam` files then.

Kate pointed out that maybe the whole `.dev` scheme could be replaced by `pin-depends`, but I'm unsure how that would work, out of my league.

2022-06-30 11:15 UTC, closed without merging

2022-06-30 11:16 UTC, ejgallego commented
> > Now that makes the opam files canonical w.r.t. the ones in the opam repos.
> 
> I don't think this is possible. If you find a way, I'm all ears.

I mean canonical w.r.t. ones in the Coq repos, sorry for the typo.

Tho, if we manage to use `dune-release` for 8.17, which is likely, then indeed the files in the main opam repos will be canonical w.r.t. to what's in the 8.17 branch tho.

2022-06-30 15:09 UTC, Zimmi48 commented
> Tho, if we manage to use `dune-release` for 8.17, which is likely, then indeed the files in the main opam repos will be canonical w.r.t. to what's in the 8.17 branch tho.

Sounds like a better plan than the proposed CI check.