Coq num analysis.1.0.0
coq/opam-coq-archive pull request #2271
Opened 2022-08-28 07:57 UTC by mmayero

Package for Numerical Analysis in Coq: Lax Milgram th, Lebesgue integration, Tonell th, Bochner th.

2022-08-28 08:25 UTC, palmskog requested changes
There is a problem with the file URL:
```
[ERROR] Failed to get sources of coq-num-analysis.1.0.0: Bad checksum
```
I recommend making a [Git tag](https://git-scm.com/book/en/v2/Git-Basics-Tagging) in the repo, which will automatically give a tarball, e.g., a previous tag has this URL: https://depot.lipn.univ-paris13.fr/mayero/coq-num-analysis/-/archive/Bochner.1.0/coq-num-analysis-Bochner.1.0.tar.gz

2022-08-28 08:25 UTC, palmskog commented on released/packages/coq-num-analysis/coq-num-analysis.1.0.0/opam
> +version: "1.0.0"
The package name and version is already given by the file path (`coq-num-analysis.1.0.0/opam`), so avoid them inside the file.
```suggestion
```

2022-08-28 08:25 UTC, palmskog commented on released/packages/coq-num-analysis/coq-num-analysis.1.0.0/opam
> +build: [make]
Usually, we want to allow file parallelism to allow the package to build faster on multicore machines. Is there are a reason not to?
```suggestion
build: [make "-j%{jobs}%"]
```

2022-08-28 08:25 UTC, palmskog commented on released/packages/coq-num-analysis/coq-num-analysis.1.0.0/opam
> +remove: [make "uninstall"]
If this is a regular Coq library, it's best to let opam take care of tracking files for installation and removal.
```suggestion
```

2022-08-29 07:17 UTC, silene commented on released/packages/coq-num-analysis/coq-num-analysis.1.0.0/opam
> +  "ocaml" { >= "4.08.1" }
Does the library come with a plugin? If not, I suggest to remove the dependency on OCaml:
```suggestion
```

2022-08-29 07:17 UTC, silene commented on released/packages/coq-num-analysis/coq-num-analysis.1.0.0/opam
> +tags: [ "keyword:real analysis" "keyword:Lax Milgram" "keyword:Lebesgue" "keyword:Tonelli" "keyword:Bochner"]
I suggest adding a few more tags for the purpose of accurate metadatas:
- `"category:..."` for proper indexing in  https://coq.inria.fr/opam/www/
- `"date:2022-08-..."` for the release date of the library (not of the Opam package)
- `"logpath:..."` for the Coq logical path where the library gets installed

2022-09-05 10:02 UTC, palmskog commented
@mmayero the key issue here is that we need a tag in your repository to get stable archive for the package. Could you create a tag called something like `1.0` in your Git repository? If so, I can take care of modifying the package here afterwards.

2022-09-06 20:45 UTC, mmayero commented
@palmskog I have pushed the tag "1.0" in our GIT repository. It compiles with Coq 8.15. I have not modified category and tag in opam file but may be I can do it later(?) Or else it should be:

category: "Real Calculus and Topology"

and modify the

tags: [ "keyword:real analysis" "keyword:Lax Milgram Theorem" "keyword:Lebesgue Integration" "keyword:Tonelli Theorem" "keyword:Bochner Integration"]

2022-09-06 20:53 UTC, palmskog commented
@mmayero great, now we have a tarball. Maybe easiest if I take care of the package definition updates, I'll incorporate the category and keywords.

2022-09-06 21:04 UTC, palmskog approved these changes

2022-09-06 21:40 UTC, merged